### ISSUE TITLE
remove angstrom

### ISSUE THREAD

**Issue by xzackli** [JuliaAstro/UnitfulAstro.jl#14]
Due to https://github.com/PainterQubits/Unitful.jl/pull/271 there is now a duplication in Unitful and UnitfulAstro for `Angstrom`. Since nobody will be using UnitfulAstro alone, just remove all references to it in this package?

(Thanks for the great package!)

**Comment by giordano** [comment]
Yes, that's a good idea.  Would you mind opening a pull request yourself? :slightly_smiling_face:

**Comment by xzackli** [comment]
Sure!

**Comment by briochemc** [comment]
Tag a new release with registrator?

**Comment by giordano** [comment]
Done, thanks for the reminder!
