### ISSUE TITLE
Adding units for other planets

### ISSUE THREAD

**Issue by siddharthlal25** [JuliaAstro/UnitfulAstro.jl#16]
While going through the documentation I saw that only the astronomical data of earth and jupiter are added. Can we add the data for the rest of the planets or is it left deliberately? @giordano

**Comment by giordano** [comment]
Sorry, I completely missed this issue!

Earth and Jupiter are the planets that are more often used as reference: Jupiter for larger planets, the Earth for smaller planets. It's not impossible to find quantities expressed in terms of other planets, but this is much less frequent.

I think the basic properties of all the planets of the Solar System are defined in https://github.com/JuliaAstro/AstroBase.jl
