### ISSUE TITLE
CompatHelper.jl

### ISSUE THREAD

**Issue by m-wells** [JuliaAstro/UnitfulAstro.jl#17]
Can we start using [CompatHelper.jl](https://github.com/bcbi/CompatHelper.jl)?  Currently, UnitfulAstro's compat entries are not up to date and it is keeping me from putting out a new version of one of my packages.

**Comment by giordano** [comment]
No problem with me if someone opens the pull request :slightly_smiling_face:

**Comment by m-wells** [comment]
See #18

**Comment by giordano** [comment]
Thanks!

**Comment by m-wells** [comment]
And last thing, we need to register with general to merge the updated Project file.
