### ISSUE TITLE
minor release to avoid warning about Gyr

### ISSUE THREAD

**Issue by islent** [JuliaAstro/UnitfulAstro.jl#24]
It would be appreciated if the master branch could make a minor release to avoid the warning:
```julia
┌ Warning: Symbol Gyr was found in multiple registered unit modules.
│ We will use the one from UnitfulAstro.
└ @ Unitful ~/.julia/packages/Unitful/9janP/src/user.jl:589
```

**Comment by islent** [comment]
Better to release in https://github.com/JuliaRegistries/General

**Comment by giordano** [comment]
I'd like to bring CI back to life (i.e., move it to GitHub Actions) before actually publishing a new release, but haven't found the time yet.  Help would be appreciated.

**Comment by islent** [comment]
OK. I will open a PR
