### ISSUE TITLE
appveyor setup

### ISSUE THREAD

**Issue by mweastwood** [JuliaAstro/UnitfulAstro.jl#3]
@kbarbary I'm trying to set up appveyor on this repository, but the builds aren't triggering when I push a new commit. I *think* this is because I need to add the webhook to the repo, but I seem to have lost access to the settings page when it was moved to JuliaAstro. Could you help me out here?

**Comment by kbarbary** [comment]
The default new repo permissions were "write". I bumped them to "admin". You should be all set, let me know if not!

**Comment by mweastwood** [comment]
Awesome, that looks like it worked, thanks!

**Comment by mweastwood** [comment]
@kbarbary I have one more request. Can you add attobot to this repository? I'm getting a 404 which I assume means you have to do it.

https://github.com/attobot/attobot

**Comment by kbarbary** [comment]
Done.
