### ISSUE TITLE
Drop support for Julia before 1.6

### ISSUE THREAD

**Issue by sefffal** [JuliaAstro/UnitfulAstro.jl#31]
Tests are currently failing on Julia 1.0.
I haven't looked into it, but perhaps we could go ahead and drop support for julia versions before the last LTS?
Older versions can still install older versions of this package.

**Comment by mileslucas** [comment]
I'm happy to do that!

**Comment by mileslucas** [comment]
~~https://github.com/JuliaRegistries/General/pull/67452~~
https://github.com/JuliaRegistries/General/pull/67453
