### ISSUE TITLE
Julia 1.0+ update

### ISSUE THREAD

**Issue by sefffal** [JuliaAstro/UnitfulAstro.jl#5]
Hi, and thank you for this useful package.
Would you mind publishing an update targeting Julia 1.0.1?
I can clone the pkg manually and everything seems to be working fine, but it's not possible to do Pkg.add("UnitfulAstro") yet.

**Comment by giordano** [comment]
Thanks for pointing this out, a new version has just been added to Metadata: https://github.com/JuliaLang/METADATA.jl/pull/19301

**Comment by sefffal** [comment]
Thanks! Tested and working on my end.
