### ISSUE TITLE
astronomical magnitudes?

### ISSUE THREAD

**Issue by m-wells** [JuliaAstro/UnitfulAstro.jl#8]
I've got an implementation that defines [Johnson and Gunn magnitudes](https://en.wikipedia.org/wiki/Apparent_magnitude#Standard_reference_values) .  Here is an example usage:
```julia
julia> include("magunit.jl")

julia> 10*Umag+12*Umag
9.840269914641551 Johnson U mag

julia> uconvert(Jy,ans)
0.2096865667835462 Jy
```
Is this something that I should submit a pull request for or should I create a separate package (UnitfulAstroMag).

**Comment by giordano** [comment]
There is already a PR about this: #4  But I think Michael never managed to finish it :pensive:

**Comment by m-wells** [comment]
I'll fork his PR and see what I can do.

**Comment by giordano** [comment]
That would be great, thanks!

**Comment by m-wells** [comment]
I've got a PR #9 that is documented and is passing tests.
